logs:
    level: debug # debug, info(default), warning, error, critical
    log_file_name: pysmt # without extension, log extension will be added automatically

health_check:
    log_info_line_at: 30 # in minutes, 0: disable

smartmetertexas: # smartmetertexas.com
    base_url: https://smartmetertexas.com/api
    username: _REPLACE_ # your user name for smartmetertexas.com
    password: _REPLACE_ # your password for smartmetertexas.com
    esiid: _REPLACE_ # your ESSID for smartmetertexas.com
    meter_number: _REPLACE_ # your Meter Number for smartmetertexas.com
    poll_interval_minutes: 60 # 0: disable, do set below 30 as smartmetertexas.com will not allow readming more than twice in an hour
    wait_interval_before_ondemand_read_minutes: 5
    force_first_read: False # if true it will attempt to read Smart Meter Texas, otherwise at poll_interval

home_assistant: # Home Assistant access details
    base_url: _REPLACE_ # your Home Assistant URL/IP, no slash (/) at the end for example: http://192.168.1.2:8123
    access_token: _REPLACE_ # your Home Assistant access token
    ha_entity: sensor.smt_reading # home assistnat entity name to be created
