version: "3"
services:
  pysmtreader:
    build:
      context: .
      dockerfile: ./dockerfile
    image: pysmtreader:0.1
    container_name: pysmtreader
    volumes:
      - ./:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
